name: install CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x install.sh
      - run: ./install.sh
      - run: shellcheck install.sh

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x install.sh
      - run: ./install.sh

  arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - run: pacman -Sy --noconfirm git
      - run: chmod +x install.sh
      - run: ./install.sh
      - run: shellcheck install.sh
